### ISSUE TITLE
Duplicate instructions

### ISSUE THREAD

**Issue by tristen** [Project-OSRM/osrm-backend#1811]
See:

![pasted_image_at_2015_12_10_01_05_pm](https://cloud.githubusercontent.com/assets/61150/11724025/6fa8b602-9f3f-11e5-9202-09b0c5c428f1.png)

**Comment by danpat** [comment]
This has to do with how the road sections are named.  All the names are different in this list, so OSRM is breaking the instructions on name changes.

**Comment by willwhite** [comment]
@MoKob this is fixed, right?

**Comment by MoKob** [comment]
@willwhite to a certain extent. The first two shouldn't announce a change anymore. I had a fix for the last one as well, but @TheMarex did not agree with the way (it was kind of hacky, since we can only do heuristics on these) and removed it. So technically some still happen.

**Comment by MoKob** [comment]
With #2263, all but one of these changes will be suppressed. the `du souvenir` part will probably not possible to suppress, unless this is just a modifier? For the rest, all other instructions should be fine.
