### ISSUE TITLE
Table and route durations consistency

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2095]
I'm building from the current head of the `rewrite/new-api` branch (at 4e9c904), then extracting and contracting with the default car profile on berlin-160314.osm.pbf from geofabrik. Then

- request `/route/v1/car/13.33,52.59;13.47,52.46` reports a `"duration":1326.1` for the route;
- request `/table/v1/car/13.33,52.59;13.47,52.46` gives a `"durations":[[0,1448.4],[1441.6,0]]` table.

In fact all `table` queries seem to yield longer durations than the corresponding `route` queries. The results used to be perfectly in line with v4.9.* using `table` and `viaroute` (up to the deci-seconds rounding).

**Comment by TheMarex** [comment]
This is fixed now! Thanks for reporting. :+1:

**Comment by jcoupey** [comment]
Thanks! I've been testing from https://github.com/Project-OSRM/osrm-backend/commit/1ea1e0fa340cc961a7b3225c56871770a3955138 with the same data setting as above, and things seem much more in line in most cases. But I'm still getting differences:

- request `route/v1/car/13.35,52.42;13.3541,52.4243` reports a `"duration":144.9` for the route;
- request `table/v1/car/13.35,52.42;13.3541,52.4243` gives a `"durations":[[0,138.3],[119.2,0]]` table.

FWIW, I get a feeling this is happening more when one of the locations have a significant distance to the nearest road segment.

**Comment by TheMarex** [comment]
@jcoupey can you compare the location these requests snap to? It is captured in the `waypoints[i].location` property for both requests. Technically the snapping behavior should be exactly the same as for the `route` query (they should use the same sub-routine).

**Comment by jcoupey** [comment]
The snapped locations are indeed the same according to the `waypoints` (for `route`), `sources` and `destinations` arrays (for `table`) that share the exact same content:

`[{"hint":"oAcAANgHAABtAAAAMwAAAIQAAAAAAAAAAAAAACZrAQAMawEApwAAAE20ywDN3R8DcLTLAKDdHwMAAAEBWgBGkQ==","name":"Brotteroder Straße","location":[13.349965,52.420045]},{"hint":"YNAAAOkCAQAAAAAAMAAAABEAAAAAAAAA-gAAAPkDAQD16AAApwAAAGDGywDP6h8DdMTLAGzuHwMAAAEBWgBGkQ==","name":"","location":[13.354592,52.423375]}]`

So my previous comment about the distance to the nearest road segment seems irrelevant here.

**Comment by jcoupey** [comment]
This seems to be solved in v5.0.0-rc.1.

The `route` and `table` durations I obtained on (quite a lot of) random pairs of locations have all been in line.

**Comment by MoKob** [comment]
Closing, since it seems to be fixed
