### ISSUE TITLE
Remove guidance data to reduce RAM usage?

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#5838]
I'm usually not interested in route information apart from duration, distance and geometry, so I'm always using OSRM with `steps=false`. My understanding is that the matching data used to generate the `steps` array in response (`RouteStep.name` and `RouteStep.ref` values among others) is still loaded in RAM. Depending on the extract size, this may amount to a lot of unused data.

First of all, I'd like to figure whether trying not to load this data is worth the trouble. I can see `osrm.names` is not that big, but `osrm.icd` is. Is there a way to evaluate the potential gain here?

**Comment by SiarheiFedartsou** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/pull/6045

**Comment by jcoupey** [comment]
#6045 is indeed related as it does save some calculation on route path data but as stated there: *this PR is a first step towards making the loading of these datasets optional* and *making these changes unlocks the optional loading of data*.

Optionally loading guidance data (or other parts of the data preprocessed by OSRM) is probably easier to implement now but it's still not possible.

**Comment by jcoupey** [comment]
While there has been no recent progress on this, I think it's worth keeping the ticket open as a feature request. It would be quite useful in many situations to be able to reduce memory requirements when some data is unused, and this would be easier to build now after #6666.
